### ISSUE TITLE
:as not supported when destructuring sequences

### ISSUE THREAD

**Issue by esp1** [nakkaya/ferret#10]
I realized that `:as` is not supported when destructuring sequences:
```
(let [[a b c :as l] (list 1 2 3)]
  (print a b c l))
```
Not a huge deal as you can rewrite the above as:
```
(let [l (list 1 2 3)
      [a b c] l]
  (print a b c l))
```
... but `:as` is a useful shorthand.

**Comment by nakkaya** [comment]
Implemented on the latest build.
