### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by zcaudate** [nakkaya/ferret#19]
I'm a little bit confused as to how `ferret.jar` is generated. Is the actual source code in `ferret.org`?

**Comment by nakkaya** [comment]
You are right ferret.org has all the source code. `Overview -> Building from Sources` page has all the instructions on how to extract the source tree. If you have `emacs` and `org-mode` installed you can just clone and run `make`. That will build the source tree and the binary.

**Comment by zcaudate** [comment]
This is great. I'll take a closer look. Would you consider publishing the jar to clojars/maven?

**Comment by nakkaya** [comment]
jars are uploaded to S3 after every travis build thats where the default download link points to. (Old versions are also available via ferret-COMMIT-ID.jar). Are you interested in calling Ferret from Clojure programatically?

**Comment by zcaudate** [comment]
Yes. that'll be the use case.

**Comment by nakkaya** [comment]
Sure. I'll configure travis to push to Clojars also.

**Comment by nakkaya** [comment]
@zcaudate Done. See `Getting Started -> Download`

**Comment by zcaudate** [comment]
brilliant! thanks.
