### ISSUE TITLE
reduce without explicit initial accumulator value produces incorrect result

### ISSUE THREAD

**Issue by mattrepl** [nakkaya/ferret#20]
It looks like `reduce`, when provided only two arguments, will invoke `f` with the first member of `sr` as `acc` and the first value of the sequence `sf` as the next `x` argument in the sequence. This in effect records the first two items in the sequence.

In other words, the expected behavior of `reduce` called as:
`(reduce f xs)`
should be the same as:
`(reduce f (first xs) (rest xs))`

But it currently is:
`(reduce f (second xs) (cons (first xs) (rest (rest xs))))`

**Comment by nakkaya** [comment]
Fixed.
