### ISSUE TITLE
Trying to use `for` throws an error.

### ISSUE THREAD

**Issue by chr15m** [nakkaya/ferret#25]
A `for` of the form:

```clojure
(for [p start-low]
  ...)
```

Throws the following error:

```
WARN unsopported form => [p start_low]
```

I am using `doseq` instead.

**Comment by nakkaya** [comment]
Hi,

The reason for this error is `for` is not yet implemented.

Best,

**Comment by kiranshila** [comment]
@nakkaya Have you made any progress on this? Or list comprehensions in general?
