### ISSUE TITLE
Using syntactic sugar fails.

### ISSUE THREAD

**Issue by chr15m** [nakkaya/ferret#26]
Might be a good idea to document prominently that one must use e.g. `(vec ...)` instead of `[...]`. This is a stumbling block for new users.

You can use the hash-map syntactic sugar `{:a 12}` successfully due to #7 fix.

**Comment by nakkaya** [comment]
Hi,

Vectors are not yet supported. They are on the roadmap. Only the data types under Runtime -> Object System -> Objects are implemented.

Best,
