### ISSUE TITLE
Question : C++ classes?

### ISSUE THREAD

**Issue by interstar** [nakkaya/ferret#29]
I'm really interested in the possibility of writing libraries in Clojure / Ferret that can be called from a C++ framework. 

Something like gen-class in Clojure.

Is this possible? Is it part of the goal for Ferret?

**Comment by nakkaya** [comment]
It is possible to call Ferret from C++. Embeddability is a primary goal of Ferret.


    ;; core.clj
    (defn say-hi
      ([]
       (println "Hello"))
      ([n]
       (println "Hello" n)))

Compile it. `ferret core.clj`. You can load `core.cpp` from C++.

    #define FERRET_DISABLE_STD_MAIN

    #include "core.cpp"

    int main(){
      using namespace ferret;
  
      run(core::say_hi());
      run(core::say_hi(), obj<string>("Dave"));
  
      return 0;
    }

**Comment by interstar** [comment]
Thanks.

That looks great :-)
