### ISSUE TITLE
:noweb-ref property inheritance failure with spacemacs on macOS

### ISSUE THREAD

**Issue by darwin** [nakkaya/ferret#3]
I wanted to start playing with Ferret on my macOS 10.12 dev machine. I'm new to emacs, so I started with spacemacs. I was able to set it up for interactive use, but the build script is failing for me.

Specifically, tangled `src/src/template.clj` has missing `<code-templates>` section and others. 

Most likely it is the issue of `:noweb-ref` property inheritance failure in spacemacs as reported here:
https://www.mail-archive.com/emacs-orgmode@gnu.org/msg112308.html

This failure is silent. Instead of a warning or error it simply emits empty string. Which confused me at first.

I tried to experiment with 
```emacs-lisp
 (setq org-use-property-inheritance t)
 (setq org-babel-use-quick-and-dirty-noweb-expansion nil)
```

but without success. I haven't found any solution to this problem.

Any ideas how to fix this?

One solution for me would be if you could stop relying on `:noweb-ref` property inheritance and explicitly name all code snippets and include them in proper places. Thanks!

**Comment by nakkaya** [comment]
I have no idea how to fix this. But you do not have to build Ferret your self you can get the latest build from [1]. (Links are to the current master. Previous versions are also available). The problem with removing noweb-ref property is that currently tangling is a problem. It takes too much time (15-20 minutes on my box) and removing noweb-ref increases it a lot.

[1] http://ferret-lang.org/

**Comment by darwin** [comment]
Thanks for answering. If speed is an issue you might consider trying `org-babel-use-quick-and-dirty-noweb-expansion`, I was experimenting with it on my machine and it made the build script run  considerably faster. Not sure about correctness.

Anyways, closing this issue.

**Comment by nakkaya** [comment]
@darwin I've enabled `org-babel-use-quick-and-dirty-noweb-expansion` and dropped all `:noweb-ref`s. Can you check if it tangles cleanly?

**Comment by darwin** [comment]
@nakkaya works for me! it completes in 9.6s on my machine:
https://gist.github.com/darwin/734761275398145264d4411ff03e18d1

Thanks for fixing this for me.
