### ISSUE TITLE
Abort During Unit Test Execution

### ISSUE THREAD

**Issue by pwhittin** [nakkaya/ferret#35]
The following file content, when "test.sh" is executed, results in an abort from the unit test executable generated and compiled by Ferret.  Any thoughts?

My computer is running Linux Mint 19.2.  with the following 'uname -a': Linux <computer-name> 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
The g++ version is: g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
The Ferret version is: ferret-lisp 0.4.0-bb18aba

File "gravity-compensation.clj":

(defn calculate-free-air-correction-local [elevation-meters]
  (* -3.086E-4 elevation-meters))

File "unit-test.clj":

(require '[gravity-compensation :as gc])

(deftest
  calculate-free-air-correction-local-test
  ((is (= -3.086E-3 (gc/calculate-free-air-correction-local 100)))))

File "test.sh":

#!/bin/bash
echo
echo "Compiling unit-test"
ferret --compile --release --disable-formatting --silent \
       --input unit-test.clj \
       --output unit-test 
echo "Executing unit-test" 
echo 
./unit-test 
echo 
echo "Done"
echo

**Comment by nakkaya** [comment]
Sorry for the late reply. I was out of town. You have one extra set of parenthesis in your test, that causes ferret to try to execute the test form removing it fixes the crash.

`unit-test.clj`

    (require '[gravity-compensation :as gc])

    (deftest calculate-free-air-correction-local-test
      (is (= -3.086E-3 (gc/calculate-free-air-correction-local 100))))

`gravity-compensation.clj`

    (defn calculate-free-air-correction-local [elevation-meters]
      (* -3.086E-4 elevation-meters))

**Comment by pwhittin** [comment]
That's a mistake I'm not proud of.  I'm very sorry I wasted your time with this.

**Comment by nakkaya** [comment]
No problem. Ferret currently does not check for any errors during compile time or runtime but its on my todo list.
