### ISSUE TITLE
native-declare in required packages are generated in reverse order

### ISSUE THREAD

**Issue by esp1** [nakkaya/ferret#5]
If calls to `native-declare` are made in a required package, they are generated in reverse order in the ferret compiler output. For instance:

```
; main.clj
(require 'xyz)

; xyz.clj
(native-declare "const int XYZ_SIZE = 123;")
(native-declare "int xyz_arr[XYZ_SIZE];")
```

Ferret will generate this from the above code:
```
int xyz_arr[XYZ_SIZE];
const int XYZ_SIZE = 123;
```

This will result in a C++ compiler error because XYZ_SIZE is not yet declared when it is used.

A workaround for this is to include both native declarations in a single use of `native-declare`, i.e.:
```
(native-declare
  "const int XYZ_SIZE = 123;
  int xyz_arr[XYZ_SIZE];")
```

**Comment by nakkaya** [comment]
Fixed.
