### ISSUE TITLE
boolean atom doesn't work when memory pool is configured

### ISSUE THREAD

**Issue by esp1** [nakkaya/ferret#6]
The following example prints alternating `false`/`true`. But if you uncomment the first line to configure the memory pool, then this will constantly print `true` - even though the value in the atom is `false`!
```
;(configure-runtime! FERRET_MEMORY_POOL_SIZE 512)

(def a (atom false))

(forever
  (println @a)
  (swap! a not)
  (sleep 500))
```
Actually, with the memory pool configured, the above example will always print `true` regardless of whether the value in the atom is `true` or `false`.

If the value in the atom is a number, however, the atom behaves appropriately, regardless of whether the memory pool is configured or not. The following example works fine:
```
(configure-runtime! FERRET_MEMORY_POOL_SIZE 512)

(def a (atom 0))

(forever
  (println @a)
  (swap! a inc)
  (sleep 500))
```

**Comment by nakkaya** [comment]
Are you running this code on an Uno? I'am trying to track this down but I can only reproduce this on an Uno (I've tried various other controllers Due Teensy, they do not exhibit this behavior.)

**Comment by esp1** [comment]
Yes, I'm running this on an Uno.

**Comment by nakkaya** [comment]
Atmega328 does not like page types other than `unsiged char` default is `size_t` when an Atmega328 is detected `unsigned char` page type is forced which fixes this behavior.

**Comment by esp1** [comment]
Awesome, thank you!

**Comment by esp1** [comment]
Actually this isn't working for me. With the latest build (ferret-lisp build: 579882e), running the following on an Uno alternately prints `true`/`false` a few times, then hangs:
```
(configure-runtime! FERRET_MEMORY_POOL_SIZE 512)

(def led_on (atom true))

(forever
  (println @led_on)
  (swap! led_on not)
  (sleep 500))
```
Here's the output, after which it hangs:
```
true
false
true
false
tr␀ 
```

Stranger still, if I add some code to blink an LED based on the value in the atom, the atom returns `true` **twice** for every time it returns `false`:
```
(configure-runtime! FERRET_MEMORY_POOL_SIZE 512)

(pin-mode 13 :output)

(def led_on (atom true))

(forever
  (println @led_on)
  (digital-write 13 (if @led_on 1 0))
  (swap! led_on not)
  (sleep 500))
```
Here's the output:
```
true
false
true
true
false
true
true
false
true
true
```
In this case it doesn't hang, but note the duplicated `true` values. Accordingly, the LED stays on for twice as long as it is off. Also note that on program start there is only one `true` value printed, but after that there are always two `true`s for every `false`.

And if I set the value of the atom to false initially, then the program hangs again with this output:
```
false
true
fa�
```

**Comment by nakkaya** [comment]
@esp1 Can you give it a shot one more time? With the latest Ferret build and latest Arduino AVR package.

**Comment by esp1** [comment]
Still not working. Now it is back to the original behavior, with the atom always deref-ing to `true`. This is with ferret-lisp build: 0362c7c and Arduino 1.8.3 with Arduino AVR Boards by Arduino version 1.6.19 in the Boards Manager.

**Comment by nakkaya** [comment]
Can you try setting the page size to `uint8_t`?

    (configure-runtime! FERRET_MEMORY_POOL_SIZE 512
                        FERRET_MEMORY_POOL_PAGE_TYPE uint8_t)

**Comment by esp1** [comment]
Yes! That works!

**Comment by nakkaya** [comment]
Awesome, I've set the default page type to uint_8 on the uno on the latest commit. If you have anymore issues just reopen the issue.

Best,

**Comment by esp1** [comment]
Excellent - thanks again!
